; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes='simple-loop-unswitch' -S < %s | FileCheck %s

; A trivial-unswitch candidate branch executes unconditionally at the top of
; every iteration, so a fully invariant condition can only take the exit edge
; on the first iteration. LCSSA PHIs in the exit block that observe loop
; header PHIs therefore always observe their start values, and can be
; rewritten to those start values when the branch is unswitched.

declare i32 @deopt(i32) nounwind

; The exit block reads both header PHIs; unswitch and substitute the start
; values (0 and 7).
define i32 @exit_phi_over_header_phi(i1 %bad, ptr %out, i32 %n) {
; CHECK-LABEL: @exit_phi_over_header_phi(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br i1 [[BAD:%.*]], label [[BAIL:%.*]], label [[ENTRY_SPLIT:%.*]]
; CHECK:       entry.split:
; CHECK-NEXT:    br label [[LOOP:%.*]]
; CHECK:       loop:
; CHECK-NEXT:    [[I:%.*]] = phi i32 [ 0, [[ENTRY_SPLIT]] ], [ [[I_NEXT:%.*]], [[CONT:%.*]] ]
; CHECK-NEXT:    [[SUM:%.*]] = phi i32 [ 7, [[ENTRY_SPLIT]] ], [ [[SUM_NEXT:%.*]], [[CONT]] ]
; CHECK-NEXT:    br label [[CONT]]
; CHECK:       cont:
; CHECK-NEXT:    [[SUM_NEXT]] = add i32 [[SUM]], [[I]]
; CHECK-NEXT:    store i32 [[SUM_NEXT]], ptr [[OUT:%.*]], align 4
; CHECK-NEXT:    [[I_NEXT]] = add nuw nsw i32 [[I]], 1
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[I_NEXT]], [[N:%.*]]
; CHECK-NEXT:    br i1 [[CMP]], label [[LOOP]], label [[EXIT:%.*]]
; CHECK:       bail:
; CHECK-NEXT:    [[IL:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ]
; CHECK-NEXT:    [[SL:%.*]] = phi i32 [ 7, [[ENTRY]] ]
; CHECK-NEXT:    [[M:%.*]] = add i32 [[IL]], [[SL]]
; CHECK-NEXT:    [[R:%.*]] = call i32 @deopt(i32 [[M]])
; CHECK-NEXT:    ret i32 [[R]]
; CHECK:       exit:
; CHECK-NEXT:    [[SUM_NEXT_LCSSA:%.*]] = phi i32 [ [[SUM_NEXT]], [[CONT]] ]
; CHECK-NEXT:    ret i32 [[SUM_NEXT_LCSSA]]
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %cont ]
  %sum = phi i32 [ 7, %entry ], [ %sum.next, %cont ]
  br i1 %bad, label %bail, label %cont

cont:
  %sum.next = add i32 %sum, %i
  store i32 %sum.next, ptr %out
  %i.next = add nuw nsw i32 %i, 1
  %cmp = icmp slt i32 %i.next, %n
  br i1 %cmp, label %loop, label %exit

bail:
  %il = phi i32 [ %i, %loop ]
  %sl = phi i32 [ %sum, %loop ]
  %m = add i32 %il, %sl
  %r = call i32 @deopt(i32 %m)
  ret i32 %r

exit:
  ret i32 %sum.next
}

; A mix of invariant and header-PHI incoming values is fine too.
define i32 @exit_phi_mixed(i1 %bad, i32 %inv, ptr %out, i32 %n) {
; CHECK-LABEL: @exit_phi_mixed(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br i1 [[BAD:%.*]], label [[BAIL:%.*]], label [[ENTRY_SPLIT:%.*]]
; CHECK:       entry.split:
; CHECK-NEXT:    br label [[LOOP:%.*]]
; CHECK:       loop:
; CHECK-NEXT:    [[I:%.*]] = phi i32 [ 0, [[ENTRY_SPLIT]] ], [ [[I_NEXT:%.*]], [[CONT:%.*]] ]
; CHECK-NEXT:    br label [[CONT]]
; CHECK:       cont:
; CHECK-NEXT:    store i32 [[I]], ptr [[OUT:%.*]], align 4
; CHECK-NEXT:    [[I_NEXT]] = add nuw nsw i32 [[I]], 1
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[I_NEXT]], [[N:%.*]]
; CHECK-NEXT:    br i1 [[CMP]], label [[LOOP]], label [[EXIT:%.*]]
; CHECK:       bail:
; CHECK-NEXT:    [[IL:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ]
; CHECK-NEXT:    [[VL:%.*]] = phi i32 [ [[INV:%.*]], [[ENTRY]] ]
; CHECK-NEXT:    [[M:%.*]] = add i32 [[IL]], [[VL]]
; CHECK-NEXT:    [[R:%.*]] = call i32 @deopt(i32 [[M]])
; CHECK-NEXT:    ret i32 [[R]]
; CHECK:       exit:
; CHECK-NEXT:    ret i32 0
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %cont ]
  br i1 %bad, label %bail, label %cont

cont:
  store i32 %i, ptr %out
  %i.next = add nuw nsw i32 %i, 1
  %cmp = icmp slt i32 %i.next, %n
  br i1 %cmp, label %loop, label %exit

bail:
  %il = phi i32 [ %i, %loop ]
  %vl = phi i32 [ %inv, %loop ]
  %m = add i32 %il, %vl
  %r = call i32 @deopt(i32 %m)
  ret i32 %r

exit:
  ret i32 0
}

; Negative: the incoming value is a loop computation, not a header PHI; its
; first-iteration value is not readily available, so do not unswitch.
define i32 @exit_phi_over_loop_computation(i1 %bad, ptr %out, i32 %n) {
; CHECK-LABEL: @exit_phi_over_loop_computation(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[LOOP:%.*]]
; CHECK:       loop:
; CHECK-NEXT:    [[I:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[I_NEXT:%.*]], [[LATCH:%.*]] ]
; CHECK-NEXT:    [[I_SCALED:%.*]] = mul i32 [[I]], 3
; CHECK-NEXT:    br i1 [[BAD:%.*]], label [[BAIL:%.*]], label [[LATCH]]
; CHECK:       latch:
; CHECK-NEXT:    store i32 [[I]], ptr [[OUT:%.*]], align 4
; CHECK-NEXT:    [[I_NEXT]] = add nuw nsw i32 [[I]], 1
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[I_NEXT]], [[N:%.*]]
; CHECK-NEXT:    br i1 [[CMP]], label [[LOOP]], label [[EXIT:%.*]]
; CHECK:       bail:
; CHECK-NEXT:    [[XL:%.*]] = phi i32 [ [[I_SCALED]], [[LOOP]] ]
; CHECK-NEXT:    [[R:%.*]] = call i32 @deopt(i32 [[XL]])
; CHECK-NEXT:    ret i32 [[R]]
; CHECK:       exit:
; CHECK-NEXT:    ret i32 0
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %latch ]
  %i.scaled = mul i32 %i, 3
  br i1 %bad, label %bail, label %latch

latch:
  store i32 %i, ptr %out
  %i.next = add nuw nsw i32 %i, 1
  %cmp = icmp slt i32 %i.next, %n
  br i1 %cmp, label %loop, label %exit

bail:
  %xl = phi i32 [ %i.scaled, %loop ]
  %r = call i32 @deopt(i32 %xl)
  ret i32 %r

exit:
  ret i32 0
}

; Negative: only part of the condition is invariant. The in-loop branch
; survives a partial unswitch, so its exit edge remains reachable on later
; iterations and the first-iteration substitution would be wrong; refuse.
define i32 @exit_phi_partial_unswitch(i1 %inv, ptr %p, ptr %out, i32 %n) {
; CHECK-LABEL: @exit_phi_partial_unswitch(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[LOOP:%.*]]
; CHECK:       loop:
; CHECK-NEXT:    [[I:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[I_NEXT:%.*]], [[CONT:%.*]] ]
; CHECK-NEXT:    [[VAR:%.*]] = load i1, ptr [[P:%.*]], align 1
; CHECK-NEXT:    [[COND:%.*]] = select i1 [[INV:%.*]], i1 [[VAR]], i1 false
; CHECK-NEXT:    br i1 [[COND]], label [[CONT]], label [[BAIL:%.*]]
; CHECK:       cont:
; CHECK-NEXT:    store i32 [[I]], ptr [[OUT:%.*]], align 4
; CHECK-NEXT:    [[I_NEXT]] = add nuw nsw i32 [[I]], 1
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[I_NEXT]], [[N:%.*]]
; CHECK-NEXT:    br i1 [[CMP]], label [[LOOP]], label [[EXIT:%.*]]
; CHECK:       bail:
; CHECK-NEXT:    [[IL:%.*]] = phi i32 [ [[I]], [[LOOP]] ]
; CHECK-NEXT:    [[R:%.*]] = call i32 @deopt(i32 [[IL]])
; CHECK-NEXT:    ret i32 [[R]]
; CHECK:       exit:
; CHECK-NEXT:    ret i32 0
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %cont ]
  %var = load i1, ptr %p
  %cond = select i1 %inv, i1 %var, i1 false
  br i1 %cond, label %cont, label %bail

cont:
  store i32 %i, ptr %out
  %i.next = add nuw nsw i32 %i, 1
  %cmp = icmp slt i32 %i.next, %n
  br i1 %cmp, label %loop, label %exit

bail:
  %il = phi i32 [ %i, %loop ]
  %r = call i32 @deopt(i32 %il)
  ret i32 %r

exit:
  ret i32 0
}
